### ISSUE TITLE
微信开发者编译时报错

### ISSUE THREAD

**Issue by ZhangEmo** [DroppingOutSpeedrun/Dropping-Out-Speedrun#1]
message：Error: 系统错误，错误码：800059,error: app.js, file not found [20230517 23:38:36][wx21c8e941022048c6]
appid: wx21c8e941022048c6
openid: o6zAJsxGtv_G1sZhdOlf4rgM7xgs
ideVersion: 1.06.2303220
osType: win32-x64
time: 2023-05-17 23:40:12

index.ts中{
	"owner": "typescript",
	"code": "2550",
	"severity": 8,
	"message": "在“PromiseConstructor”上没有“allSettled”属性。是否需要更改目标库? 请尝试将 `lib` 编译器选项更改为 es2020 或更高版本。",
	"source": "ts",
	"startLineNumber": 277,
	"startColumn": 20,
	"endLineNumber": 277,
	"endColumn": 30
}

小白 研究了一下 自己不会改 求帮助

**Comment by DroppingOutSpeedrun** [comment]
项目根目录下有一个`tsconfig.json`的文件，有一行`lib`应该包含一个`ES2020`：
```json
"lib": ["ES2020"],
```

把这个文件整个发出来看看

**Comment by ZhangEmo** [comment]
对不起  上一个问题已经解决 是我目录不对  但是现在又有一个新的问题

**Comment by ZhangEmo** [comment]
对不起 上一个问题解决了  是我的根目录选错了   这次又出现了新问题  预览页是空白的 真机也是空白的
![微信截图_20230518155200](https://github.com/DroppingOutSpeedrun/dropping-out-speedrun/assets/35828673/d45d9dec-2b3b-48e7-ac74-e06ea578b99f)
编译后提示如图
![微信截图_20230518155503](https://github.com/DroppingOutSpeedrun/dropping-out-speedrun/assets/35828673/75677b39-4d0e-471b-be21-61d9d29c7d4a)


谢谢大佬

**Comment by DroppingOutSpeedrun** [comment]
你看图1里，调试器和问题里都有些错误，你把错误发出来看看

**Comment by ZhangEmo** [comment]
大佬 之前的问题已经解决了 但是现在卡在登录上 登录不进去
![1686754091859](https://github.com/DroppingOutSpeedrun/dropping-out-speedrun/assets/35828673/8e780c98-8796-456e-8036-1ad061755bbb)

**Comment by DroppingOutSpeedrun** [comment]
我觉得这是学习通的神秘风控……？因为我这里没法复现这个问题

**Comment by DroppingOutSpeedrun** [comment]
关于登入的问题，转至 #2 讨论
